# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-28 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDBpro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dcos_host',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='\u4e3b\u673aID')),
                ('host_ip', models.CharField(max_length=255, verbose_name='\u4e3b\u673a')),
                ('host_name', models.CharField(max_length=255, verbose_name='\u4e3b\u673a\u540d')),
                ('env', models.CharField(max_length=255, verbose_name='\u533a\u57df')),
                ('cpu', models.CharField(max_length=255, verbose_name='\u4e3b\u673aCPU')),
                ('mem', models.CharField(max_length=255, verbose_name='\u4e3b\u673a\u5185\u5b58')),
                ('filesys', models.CharField(max_length=255, verbose_name='\u6587\u4ef6\u7cfb\u7edf')),
            ],
        ),
    ]
