# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-18 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDBpro', '0002_dcos_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='components',
            fields=[
                ('id', models.AutoField(max_length=255, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, verbose_name='\u4e3b\u673a')),
                ('dockerid', models.CharField(max_length=255, verbose_name='\u5bb9\u5668')),
                ('component', models.CharField(max_length=255, verbose_name='\u7ec4\u4ef6')),
                ('tag', models.CharField(max_length=255, verbose_name='tag')),
                ('value', models.CharField(max_length=255, verbose_name='value')),
            ],
        ),
    ]
