# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-19 02:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMDBpro', '0003_components'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='components',
            name='dockerid',
        ),
    ]
